### ISSUE TITLE
đọc tài liệu

### ISSUE THREAD

**Issue by kiminonawa1305** [kiminonawa1305/phan-tich-thiet-ke-he-thong#1]
ae kéo git về rồi đọc code nha. Ai có thắc mắc gì thì liên hệ lại với @MinhQuan-21130491 để làm rõ code trước khi thực hiện chức năng mưới nha

**Comment by kiminonawa1305** [comment]
@MinhQuan-21130491 Cho t xin các chức năng đã làm trong bài này đi. để còn biết mình sẽ phát triển cái j tiếp theo

**Comment by kiminonawa1305** [comment]
Ae đọc mô tả các chức năng đã làm tại đây nha
[Tài liệu tại đây](https://github.com/MinhQuan-21130491/DoAnLTWNhom60/issues?q=is%3Aissue+is%3Aclosed)

**Comment by kiminonawa1305** [comment]
Thắc mắc gì ae trao đổi trên đây luôn nha.
Rồi mình nộp cái này cho cô luôn

**Comment by MinhQuan-21130491** [comment]
oke oke

**Comment by kiminonawa1305** [comment]
@MinhQuan-21130491 hello chú.
Xin tí db điii

**Comment by kiminonawa1305** [comment]
@MinhQuan-21130491 hello chú. 
Có đó không ta
