### ISSUE TITLE
Phân công viết đặc tả chức năng

### ISSUE THREAD

**Issue by MinhQuan-21130491** [kiminonawa1305/phan-tich-thiet-ke-he-thong#2]
[Viết đặc tả cho chức năng.docx](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/files/14879500/Vi.t.d.c.t.cho.ch.c.nang.docx)

**Comment by MinhQuan-21130491** [comment]
t có phân công ai làm gì làm gì r á, mn vô coi làm nha, deadline là trước t6 tuần sau

**Comment by PhiLongNLU** [comment]
oke em

**Comment by kiminonawa1305** [comment]
Còn  phân use case thì có rồi
để t sửa tí tẹo rồi tách file lại cho he

**Comment by MinhQuan-21130491** [comment]
ok fen

**Comment by MinhQuan-21130491** [comment]
mn làm mà chưa hiểu chức năng hoạt động như nào thì coi trong issue nha,(nếu chưa hiểu nữa thì ib t nha)

**Comment by kiminonawa1305** [comment]
Hình minh họa nha các chú
Mỗi chức năng là một bảng (Lời cô nói)
![image](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/94585634/8eef057f-9592-4d1e-a014-34aa8c158d8a)

**Comment by kiminonawa1305** [comment]
[Phân tích thiết kế hệ thống.docx](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/files/14920747/Phan.tich.thi.t.k.h.th.ng.docx)
Chức năng thêm, sửa xóa sản phẩm khỏi giỏ hàng và mua sản phẩm từ giỏ hàng

**Comment by MinhQuan-21130491** [comment]
Đặc tả usecase chức năng nhóm quản lý và mua hàng nhanh
[UsecaseSpecification.docx](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/files/14945667/UsecaseSpecification.docx)

**Comment by 21130453-HuynhBaoHuyenNgoc** [comment]
[Use_case_specification.docx](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/files/14946865/Use_case_specification.docx)
Đặc tả use case cho chức năng đăng nhập, đăng ký, thay đổi thông tin

**Comment by LamHongPhong1401** [comment]
#4

**Comment by kiminonawa1305** [comment]
Bài của @NguyenHoangAnhDuong 
[muahang_dathang_chinhsua_.docx](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/files/14951360/muahang_dathang_chinhsua_.docx)
