### ISSUE TITLE
Phân công làm bài tập( deadline 25/4/2024)

### ISSUE THREAD

**Issue by MinhQuan-21130491** [kiminonawa1305/phan-tich-thiet-ke-he-thong#8]

**Comment by MinhQuan-21130491** [comment]
https://docs.google.com/document/d/1z-fTMHG3S63gh8SLujOQ0oSbpOBcI8kYzyW2da4R49g/edit?pli=1

**Comment by MinhQuan-21130491** [comment]
trong google doc có outline và phân công mn làm hết r, mn chú ý deadline và làm nha, thanks

**Comment by kiminonawa1305** [comment]
@MinhQuan-21130491 Tôi tạm thời hoàn thành công việc rồi nha. Ông lên review giúp với được không. Có gì báo t để có j t sửa lại nha. Xin lỗi vì đã làm phiền và cảm ơn vì đã giúp đỡ.

**Comment by MinhQuan-21130491** [comment]
Bài của @kiminonawa1305 oke r nha, mn tranh thủ làm xong trước 8h tối t5 để lôi file về edit nữa nha, thanks

**Comment by PhiLongNLU** [comment]
@MinhQuan-21130491 t làm xong phần việc rồi nha  : 
1. 5.2.5 Xác thực tài khoản
2. 5.2.6 Lấy lại mật khẩu
3. 5.2.6 Lấy lại mật khẩu
4. chương 1 : Mục đích đồ án
**check lại giùm t nha**
[Here](https://docs.google.com/document/d/1z-fTMHG3S63gh8SLujOQ0oSbpOBcI8kYzyW2da4R49g/edit?pli=1#heading=h.pkpoi1wdkvyy)
