### ISSUE TITLE
Phân công làm bài tập(Deadline ngày 23/5)

### ISSUE THREAD

**Issue by MinhQuan-21130491** [kiminonawa1305/phan-tich-thiet-ke-he-thong#9]
Mỗi người sẽ tự vẽ sequence diagram chức năng của mình

**Comment by MinhQuan-21130491** [comment]
ai làm xong gửi bài lên đây nha, link draw.io hoặc hình sequence

**Comment by 21130453-HuynhBaoHuyenNgoc** [comment]
![login](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/146736095/27a20543-320b-483f-9bed-9b0460033ea3)
squence_đăng nhập

**Comment by MinhQuan-21130491** [comment]
Done sequence diagram nhóm quản lý, mn check nha
![sq1](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/144221654/c8dabcc1-d59b-439a-92c8-e3c0098dbd33)
![sq2](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/144221654/ea0b19a0-5f5c-4d17-bd85-704589afce0d)
![sq3](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/144221654/d95ee3b1-cf7e-45d2-bf31-afca0942935b)
![sq4](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/144221654/a7c0d612-407f-43b5-bbe8-121fc9471c27)
![sq5](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/144221654/265cd4a0-2b40-4bb0-9c78-c3cf25a702e9)
![sq6](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/144221654/6420dcb8-b878-4858-8d6f-fbd446e4f32f)
![sq7](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/144221654/4b2177fb-9617-4f6e-ad4d-5a2c4084d547)
![sq8](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/144221654/4e485b24-bd9d-4f3a-9357-c2cbcbf480c7)
![sq9](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/144221654/d37dd47f-d67b-47c8-8c52-b2a74344404a)
![sq10](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/144221654/0b199401-d0c0-42f3-bbc9-982c29049158)
![sq11](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/144221654/4c358fe4-c68c-4ce8-84df-dcfd61b0e387)
![sq12](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/144221654/1c8e12ee-e92f-40ea-bfbe-ed68577d203c)
![sq13](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/144221654/c8735279-e55a-4aba-815a-0fcc44c7bd29)
![sq14](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/144221654/530ae02e-6676-4d2d-b790-ff43a539504e)
![sq15](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/144221654/3fad118e-b0a8-4491-89b5-ff23dd90f1c2)
![sq16](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/144221654/a3cdb8c9-5e10-44a1-9e64-52638aa6678c)

**Comment by 21130453-HuynhBaoHuyenNgoc** [comment]
![image](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/146736095/160dd96e-a4f5-4734-8e84-b6ff6ed25c8b)
squence_đangky

**Comment by 21130453-HuynhBaoHuyenNgoc** [comment]
![image](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/146736095/602851b3-f146-4528-b3ef-f216a6e91bae)
squence_capnhatthongtin

**Comment by 21130453-HuynhBaoHuyenNgoc** [comment]
![image](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/146736095/fd622fa7-440d-4b7c-b763-7438358aa787)
squence_dangnhap

**Comment by PhiLongNLU** [comment]
## Xem sản phẩm theo mục
![image](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/124154465/9d36ba67-ea6f-4079-baf5-5502e4dd9457)

## Đặt lại mật khẩu
![image](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/124154465/5d279906-dc12-4e2b-939d-7d4dc191205c)

**Comment by NguyenHoangAnhDuong** [comment]
**Mua hàng**
![mua hàng ](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/127371632/338ac428-0591-48b6-bd51-09b9ecd0c002)

**Comment by NguyenHoangAnhDuong** [comment]
**Mua hàng và thanh toán**
![image](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/127371632/7b046e4e-fedf-4ba5-b27d-7f0e8ec72a12)

**Comment by LamHongPhong1401** [comment]
**```
Thay đổi mật khẩu
![diagrams-Sequence_change_password drawio](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/128471861/3e879982-bbfc-47e7-8afe-93665c202510)

Tìm sản phẩm theo từ khóa có trong tên sản phẩm
![diagrams-Sequence_find_products drawio](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/128471861/d22a6a1f-0e28-4daa-a929-840dc6e43857)

```**

**Comment by kiminonawa1305** [comment]
Mua sản phẩm từ giỏ hàng
![diagram-sequence_ mua_san_pham_tu_gio_hang drawio](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/94585634/3cbce0b7-2d50-462a-9454-40432b025a38)


Thêm sản phẩm vào giỏ hàng
![diagram-sequence_them_san_pham_vao_gio_hang drawio](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/94585634/6092f64e-bd20-427d-8f42-bd0a3db38c9c)


cập nhật sản phẩm
![diagram-sequence_update_san_pham_vao_gio_hang drawio](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/94585634/65489913-b5c4-454a-957d-b6df0c4af6dd)


Xóa sản phẩm vào giỏ hàng
![diagram-sequence_xoa_san_pham_vao_gio_hang drawio](https://github.com/kiminonawa1305/phan_tich_thiet_ke_he_thong/assets/94585634/e7080a85-f716-4a59-9cbf-408a01a5ae31)
